### ISSUE TITLE
Bug in version 0.25: TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### ISSUE THREAD

**Issue by Idodox** [dr-prodigy/python-holidays#1280]
Ran into a bug that was solved by downgrading to 0.24.
Here's the errror:

https://github.com/dr-prodigy/python-holidays/blob/6ce469d50ff2be42cb4cd4dbc6b150fe02791edf/holidays/registry.py#L170

TypeError: object.__init__() takes exactly one argument (the instance to initialize)

`

Traceback (most recent call last):   File "/opt/main.py", line 247, in <module>     from model.predict import predict as entrypoint   File "/usr/local/lib/python3.8/site-packages/model/predict.py", line 7, in <module>     from prophet import Prophet   File "/usr/local/lib/python3.8/site-packages/prophet/__init__.py", line 7, in <module>     from prophet.forecaster import Prophet   File "/usr/local/lib/python3.8/site-packages/prophet/forecaster.py", line 19, in <module>     from prophet.make_holidays import get_holiday_names, make_holidays_df   File "/usr/local/lib/python3.8/site-packages/prophet/make_holidays.py", line 14, in <module>     import prophet.hdays as hdays_part2   File "/usr/local/lib/python3.8/site-packages/prophet/hdays.py", line 779, in <module>     class TU(Turkey):   File "/usr/local/lib/python3.8/site-packages/holidays/registry.py", line 178, in __init__     super().__init__(*args, **kwargs)
--

`

**Comment by arkid15r** [comment]
Duplicate of https://github.com/dr-prodigy/python-holidays/issues/1200.

The https://github.com/dr-prodigy/python-holidays/issues/1260 might also be useful.
