### ISSUE TITLE
US Holidays crashes for 2022

### ISSUE THREAD

**Issue by PatrickMa-EE** [dr-prodigy/python-holidays#355]
Running the package for holidays.UnitedStates(years=2022) will result in the following errors, works for every other year

Out[27]: Traceback (most recent call last):
  File "/Users/pm/.conda/envs/MRA/lib/python3.7/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/Users/pm/.conda/envs/MRA/lib/python3.7/site-packages/IPython/core/formatters.py", line 702, in __call__
    printer.pretty(obj)
  File "/Users/pm/.conda/envs/MRA/lib/python3.7/site-packages/IPython/lib/pretty.py", line 377, in pretty
    return self.type_pprinters[cls](obj, self, cycle)
  File "/Users/pm/.conda/envs/MRA/lib/python3.7/site-packages/IPython/lib/pretty.py", line 601, in inner
    for idx, key in p._enumerate(keys):
  File "/Users/pm/.conda/envs/MRA/lib/python3.7/site-packages/IPython/lib/pretty.py", line 280, in _enumerate
    for idx, x in enumerate(seq):
RuntimeError: dictionary changed size during iteration

**Comment by dr-prodigy** [comment]
Hi,
thank you for reaching out.
In your stack trace there is no reference to holidays code (which seems to exclude issues depending on the library).. would you please provide some additional information?
Thx
dr-p
