### ISSUE TITLE
Require convertdate>=2.3.0

### ISSUE THREAD

**Issue by mweinelt** [dr-prodigy/python-holidays#424]
With convertdate before 2.3.0 the tests fail, because they try to import `lag_laomer` which is only available in `convertdate>=2.3.0`, see https://github.com/fitnr/convertdate/blob/dfb84724c45a6ae1feff887cf28a3765193508d3/HISTORY.rst#230

```
ERROR: holidays (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: holidays
Traceback (most recent call last):
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/build/holidays-0.10.5/holidays/__init__.py", line 13, in <module>
    from holidays.countries import *
  File "/build/holidays-0.10.5/holidays/countries/__init__.py", line 45, in <module>
    from .israel import Israel, IL, ISR
  File "/build/holidays-0.10.5/holidays/countries/israel.py", line 16, in <module>
    from convertdate.holidays import hanukkah, lag_baomer, passover, purim, \
ImportError: cannot import name 'lag_baomer' from 'convertdate.holidays' (/nix/store/ljdqivnkfbawyrxc2gqiq51lpymlqrs1-python3.8-convertdate-2.2.1/lib/python3.8/site-packages/convertdate/holidays.py)


======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/build/holidays-0.10.5/tests.py", line 25, in <module>
    import holidays
  File "/build/holidays-0.10.5/holidays/__init__.py", line 13, in <module>
    from holidays.countries import *
  File "/build/holidays-0.10.5/holidays/countries/__init__.py", line 45, in <module>
    from .israel import Israel, IL, ISR
  File "/build/holidays-0.10.5/holidays/countries/israel.py", line 16, in <module>
    from convertdate.holidays import hanukkah, lag_baomer, passover, purim, \
ImportError: cannot import name 'lag_baomer' from 'convertdate.holidays' (/nix/store/ljdqivnkfbawyrxc2gqiq51lpymlqrs1-python3.8-convertdate-2.2.1/lib/python3.8/site-packages/convertdate/holidays.py)
```

**Comment by dr-prodigy** [comment]
Hi,
it should be fixed now and released as 0.10.5.1 on pypi.
Pls let me know, thank you very much!

**Comment by mweinelt** [comment]
LGTM.

**Comment by Henner** [comment]
I want to use holidays on a win32 2008 Server and now can not because of convertdate>=2.3.0 - I only get convertdate==2.2.2

any chance?

**Comment by KJhellico** [comment]
Holidays doesn't use `convertdate` since v.0.24.
