### ISSUE TITLE
ValueError: month must be in 1..12

### ISSUE THREAD

**Issue by CracKCatZ** [dr-prodigy/python-holidays#504]
Hey guy's,
I am currently trying to add holidays via an input but when running my script I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    for date, name in sorted(addHolidays(years=year).items()):
  File "/home/user/anaconda3/lib/python3.8/site-packages/holidays/countries/germany.py", line 81, in __init__
    HolidayBase.__init__(self, **kwargs)
  File "/home/user/anaconda3/lib/python3.8/site-packages/holidays/holiday_base.py", line 37, in __init__
    self._populate(year)
  File "test.py", line 18, in _populate
    self[date(year, day_input, int(month_input))] = add_input
ValueError: month must be in 1..12
```
This is the code I try to run:
```
from datetime import date
import datetime
import holidays

add_input = input("give me the name of the holiday: ")
day_input = int(input("give me the day of the holiday: ")
month_input = int(input("give me the month: of the holiday: ")

print(add_input)

class addHolidays(holidays.DE):
    def _populate(self, year):
        holidays.DE._populate(self, year)
        self[date(year, day_input, month_input)] = add_input

print("added a new holiday successfully!")

```

I've also tried to input different variants of parameters. For example: 
`01, 02, 03, 04, 05...12` or `1,2,3,4,5...12`

Is there something wrong with my code? If so I would be really glad if someone could tell me what I've made wrong and help  me solve this error:)

Thank's for every help and suggestion in advance:)

**Comment by dr-prodigy** [comment]
Hi, whenever creating a new date through date(...), you should set the values as here:
date(yyyy, mm, dd)
Cheers :)
