### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not NoneType

### ISSUE THREAD

**Issue by agorajek** [dr-prodigy/python-holidays#591]
The latest release has [this line ](https://github.com/dr-prodigy/python-holidays/blob/57dd2ed2b8659c76f776f10207456e5231c82099/holidays/countries/united_kingdom.py#L34) which fills in `self.state` value if `state` does not exist in kwargs but it does not help if `kwargs['state']` exists but is None. Example repro:

**Broken Version 0.12**
```
# pip show holidays
Name: holidays
Version: 0.12
...
# python
Python 3.7.12 (default, Jan  4 2022, 02:07:00)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import holidays
>>> h = holidays.UK(prov=None, state=None, years=[2020], expand=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/python3/lib/python3.7/site-packages/holidays/countries/united_kingdom.py", line 36, in __init__
    HolidayBase.__init__(self, **kwargs)
  File "/apps/python3/lib/python3.7/site-packages/holidays/holiday_base.py", line 182, in __init__
    self._populate(year)
  File "/apps/python3/lib/python3.7/site-packages/holidays/countries/united_kingdom.py", line 109, in _populate
    self._country_specific(year)
  File "/apps/python3/lib/python3.7/site-packages/holidays/countries/united_kingdom.py", line 160, in _country_specific
    if self.state not in ("Scotland") and year >= 1971:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

**Last working Version: 0.11.3.1**
```
# pip show holidays
Name: holidays
Version: 0.11.3.1
...
# python
Python 3.7.12 (default, Jan  4 2022, 02:07:00)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import holidays
>>> h = holidays.UK(prov=None, state=None, years=[2020], expand=False)
>>>
```

**Comment by MarcSkovMadsen** [comment]
Expericing same issue here.

```python
import holidays
holidays.CountryHoliday('UnitedKingdom', years=[2022])
```

**Comment by garyng2** [comment]
I got further before reaching the same error: 

    import holidays    
    import datetime
    
    datetime.date(2022, 1, 1) in holidays.CountryHoliday('US') # True (works) 

    datetime.date(2022, 1, 1) in holidays.CountryHoliday('UK') # doesn't work; error as described in title 

    '1/1/2015' in holidays.CountryHoliday('UK') # also doesn't work; error as described in title

**Comment by dr-prodigy** [comment]
Fixed in beta.. thx everyone! 👍
