### ISSUE TITLE
Can't pop New Years (observed) by name if it falls in previous year

### ISSUE THREAD

**Issue by TeejMonster** [dr-prodigy/python-holidays#625]
Version: holidays 0.12
Platform: Python 3.10.0 for Windows

Example:
``` python
import holidays


class TestClass(holidays.UnitedStates):
    def _populate(self, year):
        holidays.UnitedStates._populate(self, year)

        self.pop_named('New Year')


test_holidays = TestClass(years=2022, state='CA')

for date, name in sorted(test_holidays.items()):
    print(date, name)
```

Expected result: A list of dates and holidays

Actual result:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    test_holidays = TestClass(years=2022, state='CA')
  File ".virtualenv\lib\site-packages\holidays\countries\united_states.py", line 104, in __init__
    HolidayBase.__init__(self, **kwargs)
  File ".virtualenv\lib\site-packages\holidays\holiday_base.py", line 182, in __init__
    self._populate(year)
  File "test.py", line 8, in _populate
    self.pop_named('New Year')
  File ".virtualenv\lib\site-packages\holidays\holiday_base.py", line 363, in pop_named
    self.pop(key)
  File ".virtualenv\lib\site-packages\holidays\holiday_base.py", line 351, in pop    
    return dict.pop(self, self.__keytransform__(key))
KeyError: datetime.date(2021, 12, 31)
```

**Comment by mborsetti** [comment]
@[TeejMonster](https://github.com/TeejMonster) thanks for your report!

@dr-prodigy Thankfully this code does not generate any errors when run against the `beta` branch. I think my PRs on ensuring that only holidays for the year requested fixes it.

Maybe it's time for a new release?

**Comment by dr-prodigy** [comment]
@TeejMonster thx for your report!
@mborsetti it sounds like a good plan! :) I confirm this is already fixed in beta: I'm applying the last fixes/updates, then time for a new release! 👍
